# Generated by Django 4.2.5 on 2023-10-21 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Me',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='images/projects/')),
                ('github_link', models.CharField(max_length=300)),
                ('usage_technology', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=15)),
                ('created_at', models.CharField(max_length=100)),
                ('updated_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'SocialMedia',
            },
        ),
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='images/icons/')),
            ],
            options={
                'verbose_name_plural': 'What I Do',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250)),
                ('start_date', models.CharField(max_length=250)),
                ('end_date', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'WorkExperience',
            },
        ),
    ]
